---
title: 'Employment Equity: 2017-2020'
output: html_document
author: "Brittny Vongdara & Catalina Albury"
date: "11/15/2022"
---
# Data from previous years

Here, the plots from the repository will be repeated for additional years that the data is availble (2017-2020). 

```{r , warning = FALSE, echo =  FALSE, message = FALSE}
# Load libraries ----
library(rvest)
library(dplyr)
library(tidyr)
library(plotly)
library(flextable)
library(stringr)
library(MetBrewer)

# Function ----
remove_commas <- function(comma_cols) {
  as.numeric(gsub(
    pattern = ",",
    replacement = "",
    x = comma_cols
  ))
}

# Refer to TBS website for web scraping
url <-
  "https://www.canada.ca/en/treasury-board-secretariat/services/innovation/human-resources-statistics/diversity-inclusion-statistics/distribution-public-service-canada-employees-designated-sub-group-salary-range-"


# 2020
df_2020 <-
  merge(x = {
    ## Visible Minority and Black employees ----
    {1
      html_nodes(read_html(paste0(url,
                                  "members-visible-minorities")), "table") %>%
        html_table(fill = TRUE)
    }[[2]][-c(1, 19), c(1:4, 25)] %>% # retrieve all employees and total vm column
      rename(
        salary_range = "Salary range ($)",
        count_all = "All employees",
        count_black = "Black",
        count_vm = "Members of visible minorities"
      )
  },
  y = {
    ## Indigenous ----
    {
      html_nodes(read_html(paste0(url,
                                  "indigenous-peoples")), "table") %>%
        html_table(fill = TRUE)
    }[[2]][-c(1, 19), c(1, 11)] %>% # retrieve total indigenous column
      rename(salary_range = "Salary range ($)",
             count_indigenous = "Indigenous Peoples")
  },
  by = "salary_range",
  all = TRUE) %>%
  merge(y = {
    ## Persons with disabilities ----
    {
      html_nodes(read_html(paste0(url,
                                  "persons-disabilities")), "table") %>%
        html_table(fill = TRUE)
    }[[2]][-c(1, 19), c(1, 15)] %>% # retrieve total pwd column
      rename(salary_range = "Salary range ($)",
             count_pwd = "Persons with disabilities")
  },
  by = "salary_range",
  all = TRUE) %>% 
  mutate(across(everything(), ~ replace(., . ==  "Table 1 Footnote *" , NA))) %>% # replace foonote with NA
  mutate_at(vars(matches("count")), remove_commas) %>% # remove commas
  mutate(
    salary_range = sub(
      pattern = "    ",
      replacement = " ",
      x = salary_range
    ), # remove extra spaces in salary range column
    range_group = case_when(
      salary_range %in% c("Under 50,000",
                          "50,000 to 54,999",
                          "55,000 to 59,999"
      ) ~ "Less than $60,000",
      salary_range %in% c("60,000 to 64,999", 
                          "65,000 to 69,999"
      ) ~ "$60,000 to $69,999",
      salary_range %in% c("70,000 to 74,999", 
                          "75,000 to 79,999", 
                          "80,000 to 84,999"
                          ) ~ "$70,000 to $84,999",
      salary_range %in% c("85,000 to 89,999",
                          "90,000 to 94,999",
                          "95,000 to 99,999"
                          ) ~ "$85,000 to $99,999",
      salary_range %in% c(
        "100,000 to 149,999",
        "150,000 to 199,999",
        "200,000 to 249,999",
        "250,000 and over"
      ) ~ "Over $100,000K",
      TRUE ~ "All ranges"
    )
  ) %>% # group salary ranges to match Dr. Martin's numbers
  group_by(range_group) %>%
  summarize(
    count_all = sum(count_all, na.rm = TRUE),
    count_black = sum(count_black, na.rm = TRUE),
    count_vm = sum(count_vm, na.rm = TRUE),
    count_non_vm = count_all - count_vm,
    count_indigenous = sum(count_indigenous, na.rm = TRUE),
    count_pwd = sum(count_pwd, na.rm = TRUE)) %>% 
  ungroup() # summarize values in predetermined salary range groups

#'NOTE [needed to reorder the rows before this chunk of code]
df_2020 <- 
  df_2020[c(5, 1, 2, 3, 6, 4), ] %>% 
  mutate(
    # create new column for percentage of representation within subgroup
    per_all = round(count_all / count_all[n()] * 100, 2),
    per_black = round(count_black / count_black[n()] * 100, 2),
    per_vm = round(count_vm / count_vm[n()] * 100, 2),
    per_non_vm = round(count_non_vm / count_non_vm[n()] * 100, 2),
    per_indigenous = round(count_indigenous / count_indigenous[n()] * 100, 2),
    per_pwd = round(count_pwd / count_pwd[n()] * 100, 2),
    
    # create new column for disproportionality index (DI)
    di_all = 1,
    di_black = round(per_black / per_all, 2),
    di_vm = round(per_vm / per_all, 2),
    di_non_vm = round(per_non_vm / per_all, 2),
    di_indigenous = round(per_indigenous / per_all, 2),
    di_pwd = round(per_pwd / per_all, 2),
    
    # create new column to highlight difference from 1 for DI
    chart_black = di_black - 1,
    chart_vm = di_vm - 1,
    chart_non_vm = di_non_vm - 1,
    chart_indigenous = di_indigenous - 1,
    chart_pwd = di_pwd - 1,
  ) %>%
  select(
    range_group,
    per_all,
    di_all,
    
    per_black,
    di_black,
    chart_black,
    
    per_vm,
    di_vm,
    chart_vm,
    
    per_non_vm,
    di_non_vm,
    chart_non_vm,
    
    per_indigenous,
    di_indigenous,
    chart_indigenous,
    
    per_pwd,
    di_pwd,
    chart_pwd
  ) 

# Create table to show raw data 
# Remove chart columns amd convert to flextable object
export_table <- flextable(select(df, -contains("chart")))

# Change header labels
export_table <- set_header_labels(export_table,
                                  values = list(
                                    range_group = "Salary Range",
                                    per_all = "Percent",
                                    di_all = "DI",
                                    per_black = "Percent",
                                    di_black = "DI",
                                    per_vm = "Percent",
                                    di_vm = "DI",
                                    per_non_vm = "Percent",
                                    di_non_vm = "DI",
                                    per_indigenous = "Percent",
                                    di_indigenous = "DI",
                                    per_pwd = "Percent",
                                    di_pwd = "DI"
                                  )
)


# Create table to show raw data 
# Remove chart columns amd convert to flextable object
export_table_2020 <- flextable(select(df_2020, -contains("chart")))

# Change header labels
export_table_2020 <- set_header_labels(export_table_2020,
  values = list(
    range_group = "Salary Range",
    per_all = "Percent",
    di_all = "DI",
    per_black = "Percent",
    di_black = "DI",
    per_vm = "Percent",
    di_vm = "DI",
    per_non_vm = "Percent",
    di_non_vm = "DI",
    per_indigenous = "Percent",
    di_indigenous = "DI",
    per_pwd = "Percent",
    di_pwd = "DI"
  )
)

export_table_2020 <-  add_header_row(export_table_2020,
                     colwidths = c(1, 2,2,2,2,2,2),
                     values = c(" ", "All Employees", "Black Employees", "All Visible Minority Employees", "Non-Visible Minority Employees", "Indigenous Employees", "Employees with Disabilities"))

theme_zebra(export_table_2020)





# 2019
df_2019 <-
  merge(x = {
    ## Visible Minority and Black employees ----
    {1
      html_nodes(read_html(paste0(url,
                                  "members-visible-minorities")), "table") %>%
        html_table(fill = TRUE)
    }[[3]][-c(1, 19), c(1:4, 25)] %>% # retrieve all employees and total vm column
      rename(
        salary_range = "Salary range ($)",
        count_all = "All employees",
        count_black = "Black",
        count_vm = "Members of visible minorities"
      )
  },
  y = {
    ## Indigenous ----
    {
      html_nodes(read_html(paste0(url,
                                  "indigenous-peoples")), "table") %>%
        html_table(fill = TRUE)
    }[[3]][-c(1, 19), c(1, 11)] %>% # retrieve total indigenous column
      rename(salary_range = "Salary range ($)",
             count_indigenous = "Indigenous Peoples")
  },
  by = "salary_range",
  all = TRUE) %>%
  merge(y = {
    ## Persons with disabilities ----
    {
      html_nodes(read_html(paste0(url,
                                  "persons-disabilities")), "table") %>%
        html_table(fill = TRUE)
    }[[3]][-c(1, 19), c(1, 15)] %>% # retrieve total pwd column
      rename(salary_range = "Salary range ($)",
             count_pwd = "Persons with disabilities")
  },
  by = "salary_range",
  all = TRUE) %>% 
  mutate(across(everything(), ~ replace(., . ==  "Table 1 Footnote *" , NA))) %>% # replace foonote with NA
  mutate_at(vars(matches("count")), remove_commas) %>% # remove commas
  mutate(
    salary_range = sub(
      pattern = "    ",
      replacement = " ",
      x = salary_range
    ), # remove extra spaces in salary range column
    range_group = case_when(
      salary_range %in% c("Under 15,000",
                          "15,000 to 49,999",
                          "50,000 to 54,999",
                          "55,000 to 59,999"
                          ) ~ "Less than $60,000",
      salary_range %in% c("60,000 to 64,999", 
                          "65,000 to 69,999"
                          ) ~ "$60,000 to $69,999",
      salary_range %in% c("70,000 to 74,999", 
                          "75,000 to 79,999", 
                          "80,000 to 84,999"
                          ) ~ "$70,000 to $84,999",
      salary_range %in% c("85,000 to 89,999",
                          "90,000 to 94,999",
                          "95,000 to 99,999"
                          ) ~ "$85,000 to $99,999",
      salary_range %in% c("100,000 to 149,999",
                          "150,000 to 199,999",
                          "200,000 to 249,999",
                          "250,000 and over"
                          ) ~ "Over $100,000K",
      TRUE ~ "All ranges"
    )
  ) %>% # group salary ranges to match Dr. Martin's numbers
  group_by(range_group) %>%
  summarize(
    count_all = sum(count_all, na.rm = TRUE),
    count_black = sum(count_black, na.rm = TRUE),
    count_vm = sum(count_vm, na.rm = TRUE),
    count_non_vm = count_all - count_vm,
    count_indigenous = sum(count_indigenous, na.rm = TRUE),
    count_pwd = sum(count_pwd, na.rm = TRUE)) %>% 
  ungroup() # summarize values in predetermined salary range groups

#'NOTE [needed to reorder the rows before this chunk of code]
df_2019 <- 
  df_2019[c(5, 1, 2, 3, 6, 4), ] %>% 
  mutate(
    # create new column for percentage of representation within subgroup
    per_all = round(count_all / count_all[n()] * 100, 2),
    per_black = round(count_black / count_black[n()] * 100, 2),
    per_vm = round(count_vm / count_vm[n()] * 100, 2),
    per_non_vm = round(count_non_vm / count_non_vm[n()] * 100, 2),
    per_indigenous = round(count_indigenous / count_indigenous[n()] * 100, 2),
    per_pwd = round(count_pwd / count_pwd[n()] * 100, 2),
    
    # create new column for disproportionality index (DI)
    di_all = 1,
    di_black = round(per_black / per_all, 2),
    di_vm = round(per_vm / per_all, 2),
    di_non_vm = round(per_non_vm / per_all, 2),
    di_indigenous = round(per_indigenous / per_all, 2),
    di_pwd = round(per_pwd / per_all, 2),
    
    # create new column to highlight difference from 1 for DI
    chart_black = di_black - 1,
    chart_vm = di_vm - 1,
    chart_non_vm = di_non_vm - 1,
    chart_indigenous = di_indigenous - 1,
    chart_pwd = di_pwd - 1,
  ) %>%
  select(
    range_group,
    per_all,
    di_all,
    
    per_black,
    di_black,
    chart_black,
    
    per_vm,
    di_vm,
    chart_vm,
    
    per_non_vm,
    di_non_vm,
    chart_non_vm,
    
    per_indigenous,
    di_indigenous,
    chart_indigenous,
    
    per_pwd,
    di_pwd,
    chart_pwd
  ) 

# Create table to show raw data 
# Remove chart columns amd convert to flextable object
export_table_2019 <- flextable(select(df_2019, -contains("chart")))

# Change header labels
export_table_2019 <- set_header_labels(export_table_2019,
  values = list(
    range_group = "Salary Range",
    per_all = "Percent",
    di_all = "DI",
    per_black = "Percent",
    di_black = "DI",
    per_vm = "Percent",
    di_vm = "DI",
    per_non_vm = "Percent",
    di_non_vm = "DI",
    per_indigenous = "Percent",
    di_indigenous = "DI",
    per_pwd = "Percent",
    di_pwd = "DI"
  )
)

export_table_2019 <-  add_header_row(export_table_2019,
                     colwidths = c(1, 2,2,2,2,2,2),
                     values = c(" ", "All Employees", "Black Employees", "All Visible Minority Employees", "Non-Visible Minority Employees", "Indigenous Employees", "Employees with Disabilities"))

theme_zebra(export_table_2019)


# 2018
df_2018 <-
  merge(x = {
    ## Visible Minority and Black employees ----
    {1
      html_nodes(read_html(paste0(url,
                                  "members-visible-minorities")), "table") %>%
        html_table(fill = TRUE)
    }[[4]][-c(1, 19), c(1:4, 25)] %>% # retrieve all employees and total vm column
      rename(
        salary_range = "Salary range ($)",
        count_all = "All employees",
        count_black = "Black",
        count_vm = "Members of visible minorities"
      )
  },
  y = {
    ## Indigenous ----
    {
      html_nodes(read_html(paste0(url,
                                  "indigenous-peoples")), "table") %>%
        html_table(fill = TRUE)
    }[[4]][-c(1, 19), c(1, 11)] %>% # retrieve total indigenous column
      rename(salary_range = "Salary range ($)",
             count_indigenous = "Indigenous Peoples")
  },
  by = "salary_range",
  all = TRUE) %>%
  merge(y = {
    ## Persons with disabilities ----
    {
      html_nodes(read_html(paste0(url,
                                  "persons-disabilities")), "table") %>%
        html_table(fill = TRUE)
    }[[4]][-c(1, 19), c(1, 15)] %>% # retrieve total pwd column
      rename(salary_range = "Salary range ($)",
             count_pwd = "Persons with disabilities")
  },
  by = "salary_range",
  all = TRUE) %>% 
  mutate(across(everything(), ~ replace(., . ==  "Table 1 Footnote *" , NA))) %>% # replace foonote with NA
  mutate_at(vars(matches("count")), remove_commas) %>% # remove commas
  mutate(
    salary_range = sub(
      pattern = "    ",
      replacement = " ",
      x = salary_range
    ), # remove extra spaces in salary range column
    range_group = case_when(
      salary_range %in% c("Under 50,000",
                          "50,000 to 54,999",
                          "55,000 to 59,999"
                          ) ~ "Less than $60,000",
      salary_range %in% c("60,000 to 64,999", 
                          "65,000 to 69,999"
                          ) ~ "$60,000 to $69,999",
      salary_range %in% c("70,000 to 74,999", 
                          "75,000 to 79,999", 
                          "80,000 to 84,999"
                          ) ~ "$70,000 to $84,999",
      salary_range %in% c("85,000 to 89,999",
                          "90,000 to 94,999",
                          "95,000 to 99,999"
                          ) ~ "$85,000 to $99,999",
      salary_range %in% c("100,000 and over"
                          ) ~ "Over $100,000K",
      TRUE ~ "All ranges"
    )
  ) %>% # group salary ranges to match Dr. Martin's numbers
  group_by(range_group) %>%
  summarize(
    count_all = sum(count_all, na.rm = TRUE),
    count_black = sum(count_black, na.rm = TRUE),
    count_vm = sum(count_vm, na.rm = TRUE),
    count_non_vm = count_all - count_vm,
    count_indigenous = sum(count_indigenous, na.rm = TRUE),
    count_pwd = sum(count_pwd, na.rm = TRUE)) %>% 
  ungroup() # summarize values in predetermined salary range groups

#'NOTE [needed to reorder the rows before this chunk of code]
df_2018 <- 
  df_2018[c(5, 1, 2, 3, 6, 4), ] %>% 
  mutate(
    # create new column for percentage of representation within subgroup
    per_all = round(count_all / count_all[n()] * 100, 2),
    per_black = round(count_black / count_black[n()] * 100, 2),
    per_vm = round(count_vm / count_vm[n()] * 100, 2),
    per_non_vm = round(count_non_vm / count_non_vm[n()] * 100, 2),
    per_indigenous = round(count_indigenous / count_indigenous[n()] * 100, 2),
    per_pwd = round(count_pwd / count_pwd[n()] * 100, 2),
    
    # create new column for disproportionality index (DI)
    di_all = 1,
    di_black = round(per_black / per_all, 2),
    di_vm = round(per_vm / per_all, 2),
    di_non_vm = round(per_non_vm / per_all, 2),
    di_indigenous = round(per_indigenous / per_all, 2),
    di_pwd = round(per_pwd / per_all, 2),
    
    # create new column to highlight difference from 1 for DI
    chart_black = di_black - 1,
    chart_vm = di_vm - 1,
    chart_non_vm = di_non_vm - 1,
    chart_indigenous = di_indigenous - 1,
    chart_pwd = di_pwd - 1,
  ) %>%
  select(
    range_group,
    per_all,
    di_all,
    
    per_black,
    di_black,
    chart_black,
    
    per_vm,
    di_vm,
    chart_vm,
    
    per_non_vm,
    di_non_vm,
    chart_non_vm,
    
    per_indigenous,
    di_indigenous,
    chart_indigenous,
    
    per_pwd,
    di_pwd,
    chart_pwd
  ) 

# Create table to show raw data 
# Remove chart columns amd convert to flextable object
export_table_2018 <- flextable(select(df_2018, -contains("chart")))

# Change header labels
export_table_2018 <- set_header_labels(export_table_2018,
  values = list(
    range_group = "Salary Range",
    per_all = "Percent",
    di_all = "DI",
    per_black = "Percent",
    di_black = "DI",
    per_vm = "Percent",
    di_vm = "DI",
    per_non_vm = "Percent",
    di_non_vm = "DI",
    per_indigenous = "Percent",
    di_indigenous = "DI",
    per_pwd = "Percent",
    di_pwd = "DI"
  )
)

export_table_2018 <-  add_header_row(export_table_2018,
                     colwidths = c(1, 2,2,2,2,2,2),
                     values = c(" ", "All Employees", "Black Employees", "All Visible Minority Employees", "Non-Visible Minority Employees", "Indigenous Employees", "Employees with Disabilities"))

theme_zebra(export_table_2018)


# 2017
df_2017 <-
  merge(x = {
    ## Visible Minority and Black employees ----
    {1
      html_nodes(read_html(paste0(url,
                                  "members-visible-minorities")), "table") %>%
        html_table(fill = TRUE)
    }[[5]][-c(1, 19), c(1:4, 25)] %>% # retrieve all employees and total vm column
      rename(
        salary_range = "Salary range ($)",
        count_all = "All employees",
        count_black = "Black",
        count_vm = "Members of visible minorities"
      )
  },
  y = {
    ## Indigenous ----
    {
      html_nodes(read_html(paste0(url,
                                  "indigenous-peoples")), "table") %>%
        html_table(fill = TRUE)
    }[[5]][-c(1, 19), c(1, 11)] %>% # retrieve total indigenous column
      rename(salary_range = "Salary range ($)",
             count_indigenous = "Indigenous Peoples")
  },
  by = "salary_range",
  all = TRUE) %>%
  merge(y = {
    ## Persons with disabilities ----
    {
      html_nodes(read_html(paste0(url,
                                  "persons-disabilities")), "table") %>%
        html_table(fill = TRUE)
    }[[5]][-c(1, 19), c(1, 15)] %>% # retrieve total pwd column
      rename(salary_range = "Salary range ($)",
             count_pwd = "Persons with disabilities")
  },
  by = "salary_range",
  all = TRUE) %>% 
  mutate(across(everything(), ~ replace(., . ==  "Table 1 Footnote *" , NA))) %>% # replace foonote with NA
  mutate_at(vars(matches("count")), remove_commas) %>% # remove commas
  mutate(
    salary_range = sub(
      pattern = "    ",
      replacement = " ",
      x = salary_range
    ), # remove extra spaces in salary range column
    range_group = case_when(
      salary_range %in% c("Under 50,000",
                          "50,000 to 54,999"
                          ) ~ "Less than $55,000",
      salary_range %in% c("55,000 to 59,999", 
                          "60,000 to 64,999"
                          ) ~ "$55,000 to $64,999",
      salary_range %in% c("65,000 to 69,999", 
                          "70,000 to 74,999", 
                          "75,000 to 79,999"
                          ) ~ "$65,000 to $79,999",
      salary_range %in% c("80,000 to 84,999", 
                          "85,000 to 89,999",
                          "90,000 to 94,999"
                          ) ~ "$80,000 to $94,999",
      salary_range %in% c("95,000 to 99,999", 
                          "100,000 and over"
                          ) ~ "Over $95,000K",
      TRUE ~ "All ranges"
    )
  ) %>% # group salary ranges to match Dr. Martin's numbers
  group_by(range_group) %>%
  summarize(
    count_all = sum(count_all, na.rm = TRUE),
    count_black = sum(count_black, na.rm = TRUE),
    count_vm = sum(count_vm, na.rm = TRUE),
    count_non_vm = count_all - count_vm,
    count_indigenous = sum(count_indigenous, na.rm = TRUE),
    count_pwd = sum(count_pwd, na.rm = TRUE)) %>% 
  ungroup() # summarize values in predetermined salary range groups


#'NOTE [needed to reorder the rows before this chunk of code]
df_2017 <- 
  df_2017[c(5, 1, 2, 3, 6, 4), ] %>% 
  mutate(
    # create new column for percentage of representation within subgroup
    per_all = round(count_all / count_all[n()] * 100, 2),
    per_black = round(count_black / count_black[n()] * 100, 2),
    per_vm = round(count_vm / count_vm[n()] * 100, 2),
    per_non_vm = round(count_non_vm / count_non_vm[n()] * 100, 2),
    per_indigenous = round(count_indigenous / count_indigenous[n()] * 100, 2),
    per_pwd = round(count_pwd / count_pwd[n()] * 100, 2),
    
    # create new column for disproportionality index (DI)
    di_all = 1,
    di_black = round(per_black / per_all, 2),
    di_vm = round(per_vm / per_all, 2),
    di_non_vm = round(per_non_vm / per_all, 2),
    di_indigenous = round(per_indigenous / per_all, 2),
    di_pwd = round(per_pwd / per_all, 2),
    
    # create new column to highlight difference from 1 for DI
    chart_black = di_black - 1,
    chart_vm = di_vm - 1,
    chart_non_vm = di_non_vm - 1,
    chart_indigenous = di_indigenous - 1,
    chart_pwd = di_pwd - 1,
  ) %>%
  select(
    range_group,
    per_all,
    di_all,
    
    per_black,
    di_black,
    chart_black,
    
    per_vm,
    di_vm,
    chart_vm,
    
    per_non_vm,
    di_non_vm,
    chart_non_vm,
    
    per_indigenous,
    di_indigenous,
    chart_indigenous,
    
    per_pwd,
    di_pwd,
    chart_pwd
  ) 

# Create table to show raw data 
# Remove chart columns amd convert to flextable object
export_table_2017 <- flextable(select(df_2017, -contains("chart")))

# Change header labels
export_table_2017 <- set_header_labels(export_table_2017,
  values = list(
    range_group = "Salary Range",
    per_all = "Percent",
    di_all = "DI",
    per_black = "Percent",
    di_black = "DI",
    per_vm = "Percent",
    di_vm = "DI",
    per_non_vm = "Percent",
    di_non_vm = "DI",
    per_indigenous = "Percent",
    di_indigenous = "DI",
    per_pwd = "Percent",
    di_pwd = "DI"
  )
)

export_table_2017 <-  add_header_row(export_table_2017,
                     colwidths = c(1, 2,2,2,2,2,2),
                     values = c(" ", "All Employees", "Black Employees", "All Visible Minority Employees", "Non-Visible Minority Employees", "Indigenous Employees", "Employees with Disabilities"))

theme_zebra(export_table_2017)

```

# Calculating Quantiles for Salary Ranges


```{r , warning = FALSE, echo =  FALSE, message = FALSE}




```